version: '3.4'
services:
    database:
        image: mongo
        restart: always
        volumes:
          - data:/data/db
        
    myappli:
        build:
          context: .
          dockerfile: Dockerfile
        depends_on:
          - database
        volumes:
          - .:/app
        ports:
          - 3000:3000
volumes:
    data:
